version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins Web UI
      - "50000:50000" # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-network

  # If you want to add a database, for example, you can add:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: jenkins
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - jenkins-network

volumes:
  jenkins_home:
  #postgres_data:

networks:
  jenkins-network:
    driver: bridge
