services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amreen123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python backend/app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=amreen123
      - DB_HOST=db
      - DB_PORT=5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 22bcaf10@kristujayanti.com # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: amreen123 # Replace with your password
    ports:
      - "5050:80" # Expose pgAdmin on localhost:5050
    depends_on:
      - db

volumes:
  postgres_data: